### ISSUE TITLE
/api/assets/collection/{idCollection}/ Not Found

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/asset-manager#157]
The endpoint to get assets belonging to a specific collection is not Found on staging. @asimonw @georgemillard do you know if this has been removed by mistake?

linked to: https://github.com/emfoundation/ce100-app/issues/1108

**Comment by asimonw** [comment]
@SimonLab Sorry about that! The endpoint was lost during a refactor. It should be back on staging tomorrow.

**Comment by georgemillard** [comment]
@SimonLab This should be fixed now. Let me know if there are any issues!

**Comment by SimonLab** [comment]
working for me 👍
