### ISSUE TITLE
Give urls the name parameter so they can be accessed/changed dynamically

### ISSUE THREAD

**Issue by MertonL** [emfoundation/asset-manager#158]
As a developer I want to be able to change the url endpoints of the asset manager without it breaking any templates or code that reference them.  
Providing a name parameter in Django `url()` patterns and simple router's allows the url to be referenced in the code and templates without having to hardcode it - meaning the code will not break if the url changes in the future. 

This is especially needed in the API urls file, and will be needed when we begin front-end development.

**Comment by MertonL** [comment]
- This allows for the use of the reverse('url_name') function in code, and {% url 'url_name' %} in templates.

**Comment by asimonw** [comment]
@MertonL Now that #212 is merged in, happy to close this one?
