### ISSUE TITLE
Not possible to create assets with special characters in the title

### ISSUE THREAD

**Issue by asimonw** [emfoundation/asset-manager#163]
Certain content which already existed on the CE100 app contains the following characters:
`' " & , . ( )`

Which of these characters should we allow and how to we cater for the need to use the ones that we won't allow?

**Comment by georgemillard** [comment]
Easy to implement this change. Just need to choose which chars to allow.

I am happy with & and ,
' seems reasonable

I think people can live without " . ( )

What do you think? I can't see a technical reason to disallow any, though, unless it may affect search in the future...

**Comment by asimonw** [comment]
@georgemillard For me that's fine, but might warrant a conversation with content owners.
I'll send through the examples which required . and () so you can get an idea. People can definitely do with one pair of quotes, but it might be frustrating to get an error because they're using the wrong ones, so we'd need to add some instructions. All in all, it could be more straight forward to be more permissive.
