### ISSUE TITLE
Replace "change" link with an edit button

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#175]
The current "change" link next to Assets and Folders is too small and its use is not clear.
An edit button would be more useful.

**Comment by georgemillard** [comment]
Change link replaced with Edit button.
Next step is to remove change link from file_manager Model list.

**Comment by asimonw** [comment]
@georgemillard Here again, not sure what I'm looking at. Would it be possible to include a description of where the link/button is located or a screenshot?

**Comment by georgemillard** [comment]
![screen shot 2018-01-23 at 09 12 19](https://user-images.githubusercontent.com/25058990/35267275-a02b70c6-001d-11e8-982d-42a14738e2ac.png)

**Comment by georgemillard** [comment]
The change link is the bit above the asset name text box. It includes the path, a pencil icon and the Change link itself. It links to the asset's Edit page.

**Comment by asimonw** [comment]
Looks cleaner indeed!
