### ISSUE TITLE
Review how to handle special chars, including spaces, for file names.

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#176]
We now allow special chars and whitespace in Asset names, but not filenames. It would be good to review this.

**Comment by asimonw** [comment]
One thing to keep in mind is that filenames end up in urls, so it does make sense to restrict the allowed chars if only for that reason.

**Comment by georgemillard** [comment]
Having looked on the AWS site, the following chars are safe for S3 keys: !, -, _, ., *, ', (, and )
Spaces, however, are not recommended.

#188 will provide a clearer error message when file names are invalid.

**Comment by georgemillard** [comment]
I have also noticed that django storages (the package we use to manage file upload to s3) is stripping double braces ie () before file validation. So foo()bar.txt will pass validation even if ()'s are not allowed. The file will be saved as foobar.txt. This is an edge case but another reason for some js validation to be implemented.

**Comment by MertonL** [comment]
Another issue with () being removed before validation is that it allows for duplicate filenames in the same folder. 

*ex.*
`test().txt` -> `test.txt`
Then if you try and save that same file in a different asset, it passes. As `test().txt` differs from the saved `test.txt`, resulting in two `test.txt` files.
