### ISSUE TITLE
Django Admin File Manager page - change link is misleading - resolve

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#183]

**Comment by georgemillard** [comment]
/admin/file_manager/
I removed the change link, as the model names eg Assets, Collection, etc link to the same page as the change link did but are clearer from a navigation point of view.

**Comment by asimonw** [comment]
@georgemillard Where was that change link? Hard to check whether something isn't there anymore 😜

**Comment by georgemillard** [comment]
![screen shot 2018-01-23 at 09 34 54](https://user-images.githubusercontent.com/25058990/35268332-b7a482bc-0020-11e8-8722-4f18a824fd80.png)

**Comment by georgemillard** [comment]
The change link to the right links to the same page as the model name, in this case "Assets". Change seems an odd name for a link to a page showing all the Assets, so I have removed it for now.

**Comment by asimonw** [comment]
Understood and LGTM
