### ISSUE TITLE
Front-end build pipeline

### ISSUE THREAD

**Issue by asimonw** [emfoundation/asset-manager#191]
Set up and integrate front-end build pipeline. This will include
- [x] Set up gulp for dev flow
- [x] Integrate it with Django's dev server (just used simple proxy)
- [ ] Set up gulp for production build
- [ ] Make sure Django serves the produced assets properly in production

**Comment by asimonw** [comment]
It looks like a common way to achieve the integration is by using [webpack-bundle-tracker](https://github.com/ezhome/webpack-bundle-tracker) and [django-webpack-loader](https://github.com/ezhome/django-webpack-loader).

A fairly old post, but this argues convincingly for treating the front-end build separately from Django processes: http://owaislone.org/blog/modern-frontends-with-django/

**Comment by asimonw** [comment]
@georgemillard I've added this to in progress for sprint 4 as I'll need something set up to work with SASS anyway.

**Comment by asimonw** [comment]
Making webpack play nice with Django feels a bit convoluted (or at least would require further investigation). Setting up Gulp will be simpler to get us going. @MertonL @georgemillard are you happy with that?

**Comment by georgemillard** [comment]
@asimonw Happy with gulp for now, and we might try some packages that benefit our other sites.

**Comment by asimonw** [comment]
@georgemillard As the production steps outlined above will now be handled by Django's collectstatic, to be configured in #241, shall we close this one?
