### ISSUE TITLE
Couch placement not symmetrical

### ISSUE THREAD

**Issue by dalwal08** [emfoundation/asset-manager#204]
George, your couch is not perfectly aligned with the picture and lights on the wall...

**Comment by dalwal08** [comment]
Still not fixed...but excuse provided.

**Comment by kareninsignares** [comment]
Excuse not valid...

**Comment by fannyBkane** [comment]
@dalwal08 Can you update the issue with the excuse? The world wants to know.

**Comment by dalwal08** [comment]
Well, I'm glad you asked @fannyBkane ...

The user responded and stated that the couch is, in fact, symmetrical. The excuse offered was that the computer providing the live feed was offset at such an angle that it gave the incorrect impression of asymmetry. The user attempted to manipulate the movement of the computer to illustrate the effect.

As @kareninsignares says, "not valid".

**Comment by georgemillard** [comment]
Glad you are all getting plenty of practice working with GitHub :D

**Comment by asimonw** [comment]
I am willing to embrace this spam...
