### ISSUE TITLE
Copy production database and S3 bucket contents to staging

### ISSUE THREAD

**Issue by asimonw** [emfoundation/asset-manager#208]
This will for one thing ensure that all tag ids are the same in both systems, which will help significantly in testing the integration with cello going forward.

**Comment by asimonw** [comment]
This issue is coupled with https://github.com/emfoundation/ce100-app/issues/1267.
Ideally this issue is tackled before that one.

**Comment by asimonw** [comment]
@georgemillard LGTM!

Shall I leave this issue open until you've checked how it affected migrations?

**Comment by georgemillard** [comment]
Lets leave it open for now as a reminder, thanks.

**Comment by MertonL** [comment]
Closing as this is no longer relevant - tags are now the same on both systems.
