### ISSUE TITLE
Technical prototype for list view with complex filtering options

### ISSUE THREAD

**Issue by asimonw** [emfoundation/asset-manager#213]
This includes:
+ What are the responsibilities of the backend (Django) and frontend (Vue?)
+ Do we want to use Ajax for filtering interactions
+ Use Webpack or Gulp as a build tool?
+ How does this play with the Django architecture
+ How do we use CSS? (SASS, PostCSS, frameworks like Bulma, Tachyons?)
+ How to separate production and dev packages in requirements.txt

**Comment by georgemillard** [comment]
@asimonw As part of the build work perhaps you could look into managing python dependencies for different environments, as at the moment a lot of dev packages are pushed to production. Something similar to node's npm install --save-dev

**Comment by asimonw** [comment]
@georgemillard Good idea. I'll add that to the list in the top comment.
