### ISSUE TITLE
Setup and implement the use of git flow

### ISSUE THREAD

**Issue by MertonL** [emfoundation/asset-manager#224]
As we're about to begin our build for the public user interface, I figured now is the best time to implement a more strict usage of git-flow.

I have trialled a cli tool called `git-flow-avh`, and it is the predecessor of the previous `git-flow` which is now deprecated.

**Thought process**
By all using this tool where possible, it should aid us in making us follow the git-flow methodology consistently and helping with more strict releases/versioning.

## Setup
The tool does not affect the repository and so is on a user basis, but instead adds a selection of useful commands that run a group of git commands for you.
1. Install [git-flow-avh](https://github.com/petervanderdoes/gitflow-avh)
2. Install [git-completion](https://github.com/petervanderdoes/git-flow-completion/wiki/Install-Bash-git-completion) & [git-flow-completion](https://github.com/petervanderdoes/git-flow-completion) [**Optional, but recommended**] 
3. Run `git flow init`, and leave all as default

## Usage
These documents explain how to use the tool more fully and are better at explaining than I am: [HowTo git-flow](https://jeffkreeftmeijer.com/git-flow/) and [git-flow cheatsheet](http://danielkummer.github.io/git-flow-cheatsheet/)

However this is my suggestion for our usage (feel free to add your comments) from the research i've done around peer coding and group dev work:
### Standard Development & Code reviews
1. To create a new feature branch called `feature/your-feature-name` (or if we still use the issue-xx convention, then feature/issue-xx) use:
```
git flow feature start your-feature-name
``` 

2. Add and commit like you normally would with git, then push. 
3. Create a pull request, get the code reviewed and approved but *do not* use github to pull the request.
4. Instead, the dev that is responsible with merging the pull request should run the feature finish command:
```
git flow feature finish your-feature-name
```
This merges the feature branch with develop, and deletes the branch and git will automatically close the pull request.

### Releases & Versioning
1. To create a new release, run this command:
```
git flow release start 1.0.0
```
This will branch off of develop, creating the release branch.
2. Do any small fixes and build processes on this branch
3. If any changes, make a pull request, then the dev responsible should run:
```
git flow release finish 1.0.0
```
This will ask you to comment a few times on the merges, it will also add a tag which you should make a comment in the merge stating the version (this will be commented out by default, so uncomment). Then it will merge the release branch and tag into develop and master.

### Other notes
There are also other branches that can be used, such as hotfixes, which are affectively the same as a feature branch, however it branches off of master, and is used solely for emergency quick fixes.

@asimonw @georgemillard Let me know your thoughts on this, and ideas around what we want our naming conventions to be (we could go down the route of `issue/xx` rather than `feature/xx` if we wanted) are welcome

**Comment by asimonw** [comment]
@MertonL Sounds interesting! One immediate question: what's the reason for not using GitHub to merge in the PR? Seemed like a handy way of doing it.

**Comment by MertonL** [comment]
@asimonw I think the main benefit is that git-flow does a few extra steps behind the scenes, like not using fast forward to keep commit/branch history. 
However It would be good to see if using GitHub's PR method interferes with the flow in any way - I do not think it would (for feature branches at least) but it would be worth testing as I agree it is a easier way.
