### ISSUE TITLE
Build Home Page

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#226]
- [x] Dummy search link to "Coming Soon..." page
- [x] Clickable Topic List

Estimate 2 hours

**Comment by georgemillard** [comment]
See latest prototype: https://www.figma.com/proto/feXDEOrWavhHU1wsw8ltbN/MVP-mobile-V.2?node-id=1%3A2&scaling=contain

**Comment by georgemillard** [comment]
@asimonw Can the whole Topic block be clickable, rather than just the Topic title?

**Comment by asimonw** [comment]
This can be tested on staging. The actual search page still needs to be built, so it's just the icon for now.

**Comment by asimonw** [comment]
@georgemillard Good point, I forgot to make that change. Will do.

**Comment by fannyBkane** [comment]
Bearing in mind icons will be added (#232), and potentially be animated (#256). 

Also, can you confirm @georgemillard that the 'hook' in the hero need not be updated before we run user tests? 

Otherwise, LGTM!

**Comment by georgemillard** [comment]
@fannyBkane lets discuss the 'hook' and order tasks in the sprint planning today.
