### ISSUE TITLE
Build Asset Page

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#230]

**Comment by georgemillard** [comment]
See latest prototype: https://www.figma.com/proto/feXDEOrWavhHU1wsw8ltbN/MVP-mobile-V.2?node-id=1%3A2&scaling=contain

**Comment by georgemillard** [comment]
@fannyBkane to review use of uploaded at

**Comment by georgemillard** [comment]
First step for "Share" to be open an email client with default text in Subject and link in Body. Share link 
to Asset page to give it context.

Authors to be renamed to Collaborators and have a default icon - not differentiate between individuals and organisations for now.

**Comment by georgemillard** [comment]
Tags not clickable for now

**Comment by asimonw** [comment]
Note to self: still to do
+ make back link work
+ improve spacing
+ add icon based on format
+ improve font sizes and colours

**Comment by fannyBkane** [comment]
Can the word link be change to 'Go to website'?

![screen shot 2018-03-12 at 15 28 33](https://user-images.githubusercontent.com/20577339/37293109-573fee42-260a-11e8-9897-de5172ff394a.png)

By the way, I noticed the case of the buttons text was written in uppercase. Is it possible to use a css property to transform the text in upper-case instead? That way we can consider future changes more easily :)

**Comment by fannyBkane** [comment]
The Header 1 is currently 32 px on desktop on staging. Was it generated by the default typography scale on Bulma? (fyi it is 48px on the mockups)

**Comment by fannyBkane** [comment]
Could the top/below padding in the hero be tweaked so the value have the same ratio as on the screenshot?  ![screen shot 2018-03-12 at 15 39 10](https://user-images.githubusercontent.com/20577339/37293627-c57d7c52-260b-11e8-809f-f2ee4e7c7f3b.png)

**Comment by asimonw** [comment]
@fannyBkane I'll tweak those values, no problem. I didn't have the exact numbers when developing.
