### ISSUE TITLE
Update all pages to be in line with design

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#231]
Two parts:
- [x] update mobile
- [x] update desktop

To be split into two subtasks when I get to it. [ADDED BY ALEX]

**Comment by asimonw** [comment]
@fannyBkane This can now be tested on staging. Make sure to Shift refresh to get the latest CSS (no automatic cache busting in place yet).

There are more issues in `please test` but I suggest we collect visual design feedback here.

**Comment by fannyBkane** [comment]
![screen shot 2018-03-12 at 15 13 35](https://user-images.githubusercontent.com/20577339/37292316-985f4c62-2608-11e8-9eb5-9f3a04b57754.png)
LGTM. One thing: the full EMF logo was used on desktop. I think it's fine to leave as it is on staging now. But we shall open an separate issue to update the name/logo, as it is likely to be updated with a new wordmark.

**Comment by asimonw** [comment]
@fannyBkane I actually overlooked that. I thought we wouldn't put the EMF name in that top corner to avoid confusion. 

But yes, sounds good to create a new issue to update logo/name once we have one.
