### ISSUE TITLE
Link search icon to "Coming soon" 

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#234]
@asimonw to decide on best way to implement this in this sprint. Choices are extra page or pop-up.

**Comment by asimonw** [comment]
@fannyBkane Any ideas for what to put on this page? Could be something fun but quick to do? Like one of those "Under construction" pages..

**Comment by asimonw** [comment]
@georgemillard The back button you added always takes you back to the homepage (effectively performing the same function as the home icon). We'd probably want to have it go back to the page the user is coming from? (maybe not necessary for the MVP though)

**Comment by fannyBkane** [comment]
Looks good, could a link be added under _coming soon_ that said **'Continue browsing the site'**? (link to topic page)

**Comment by asimonw** [comment]
@fannyBkane @georgemillard I'll add that link that Fanny suggests and remove the back button at the top, since that one makes less sense the way it works at the moment (see my previous comment).
