### ISSUE TITLE
Prevent search engines from indexing/listing staging

### ISSUE THREAD

**Issue by asimonw** [emfoundation/asset-manager#240]
There are two things we could do, with increasing effectiveness:
- [x] Put the following two lines in a `robots.txt` file in the root folder:
```
User-agent: *
Disallow: /
```
This only prevents the site from being indexed (content crawled), but it might still be listed.

It seems to be better to serve the file through Nginx. It looks like you can point to the location of the file by adding this to the config:
```
location  /robots.txt {
    alias  /path/to/static/robots.txt;
}
```
**Important note:** don't check the `robots.txt` file into git (add it to .gitignore). Add it on the staging server directly. We don't want this on the live server. (Unless we configure Nginx to serve a different file depending on host domain?)

- [x] Add basic authentication at the Nginx level. This will more effectively prevent the site from being listed.

**Comment by georgemillard** [comment]
Hey @asimonw, by root folder do you mean the repository root, currently /home/gbmillard/projects/asset-manager/ ?

**Comment by asimonw** [comment]
@georgemillard I'm assuming the root from which Nginx is serving. I think that would prevent everything on staging (API, admin, user interface) from being indexed.
