### ISSUE TITLE
Add optimisation and cache busting of static assets to collectstatic

### ISSUE THREAD

**Issue by asimonw** [emfoundation/asset-manager#241]
This seems to be a good guide for adding cache busting with a Django plugin: http://staticfiles.productiondjango.com/blog/setting-up-static-file-caching/

This should play nice with the pipeline plugin that @MertonL mentioned.

**Comment by georgemillard** [comment]
@asimov manifest caching now enabled, and I've checked that staging is using the hashed files. There is nothing in place to remove old versions however. The simplest solution would be to delete the static folder before running collect static. I could do this as an alias on the server, but perhaps a gulp script would be a more elegant solution?

**Comment by asimonw** [comment]
@georgemillard As we're not running any Gulp build script on the server, it'd be overhead to add Node and Gulp just for that. Maybe there's a Django plugin for it? Otherwise a simple Python script might do, and run that before collect static as part of the same alias?

**Comment by georgemillard** [comment]
I've added a command to the `dam_restart` alias that clears the static folder, then runs `collectstatic` automatically after restarting uwsgi.
