### ISSUE TITLE
Update brand colours

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/asset-manager#247]

**Comment by fannyBkane** [comment]
- topic cards:
box-shadow default: 0 1px 1px 0 rgba(10, 16, 34, .2)
box-shadow hover: 0 10px 30px -5px rgba(10, 16, 34, .2)

- body (on all pages)
background colour: #f9f9fa

**Comment by fannyBkane** [comment]
@georgemillard @MertonL @asimonw Primary functional colour (sign off by Sas) `#3E4DB9`: ![asset](https://user-images.githubusercontent.com/20577339/37150429-91be3ea0-22c9-11e8-8d48-3be222ec9cde.png)
![homepage](https://user-images.githubusercontent.com/20577339/37150430-91db21c8-22c9-11e8-8891-77d247596bf4.png)
![list](https://user-images.githubusercontent.com/20577339/37150431-91f60ac4-22c9-11e8-9ba0-7fe743525b77.png)

**Comment by asimonw** [comment]
@fannyBkane Looks good to me!

**Comment by georgemillard** [comment]
@fannyBkane nice 😄

**Comment by fannyBkane** [comment]
@asimonw could we have the  same hover state on 
![screen shot 2018-03-12 at 15 01 53](https://user-images.githubusercontent.com/20577339/37291361-5f6cd228-2606-11e8-9ca5-0a43b0ffde9e.png)
thank on the search icon?

One question: is the default text colour Bulma's? 

Otherwise, lgtm :)

**Comment by asimonw** [comment]
@fannyBkane We'd have to use an svg format for the logo in order to be able to do that. Just email me the svg if you prefer that.

And yes, so far it's Bulma's default text colour. Happy to change it if you prefer.

**Comment by fannyBkane** [comment]
> @fannyBkane We'd have to use an svg format for the logo in order to be able to do that. Just email me the svg if you prefer that.

I can send a svg across, np. Is the svg going to be displayed ok on most browsers?


> And yes, so far it's Bulma's default text colour. Happy to change it if you prefer.

That's fine, looks good. Just wanted to clarify. Cheers!

**Comment by asimonw** [comment]
@fannyBkane You're right that I'd need to put in some work to make the SVG logo work well on IE/Edge (possibly with PNG fallback). Shall we create a new issue for it and prioritise it in the next sprint @georgemillard ?
