### ISSUE TITLE
Sprint 4 User Testing

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#265]
Link to Test Doc:
https://docs.google.com/document/d/1nLVzre89YXoE9YgzKM5NtsAYYYXBA5HP9AjZMaFq7kw/edit?ts=5aaa50eb#heading=h.tvuikawr528b

**Comment by fannyBkane** [comment]
@georgemillard @asimonw @MertonL 4 tests were run, 1 more is scheduled (on Tuesday). This is a suggestion on next steps to take, once the last test is completed:
 
- The results will be analysed and help validate/unvalidate assumptions
- We'll see if the vision strategy for the dams need reviewing based on the learnings
- We'll prioritise the learnings/issues, based on the vision/strategy
- We'll brainstorm to come up with improvements, new features, new assumptions to take forward into the next Sprint.

**Comment by MertonL** [comment]
added to wiki
