### ISSUE TITLE
Define exponential problem/principle

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#266]
### Digital Asset Management System (DAM) Exponential Problem/Solution 

We produce a large amount of high-quality content. However, we currently do not have a single place to store and manage it, or a consistent way of finding and sharing it. 

The DAM will aim to provide a single place to store and manage our content, while the interfaces we build upon it will allow our Users to access it.

#### How does the DAM support EMF Business Strategy

- By increasing the circularity of our content - maintaining its highest value and availability within the system.
- By facilitating the implementation of our Content Strategy

#### User Groups 

| User Groups | Interface | Needs |
|--------------|----------|--------|
| Admin | Admin Interface | Manage the system, user accounts, security
| Content Owner | Admin Interface | Upload, Read, Edit, Delete content
| EMF User | EMF Interface | Find and access all DAM content
| Public User | Public Interface | Find and access all public DAM content
| Cello User | Cello (via API) | Find and access Cello Library (stored on the DAM)

#### Component definitions

The DAM will be a space to store and manage all EMF "latest-version" resources.
Additionally, it will store references to external content where relevant (ie Cello Library).

The EMF Interface will allow EMF Users to find and access all items on the DAM. This will allow them to be more effective in their work, to utilise EMF content more easily and to have an overview and access to the most relevant circular economy knowledge. 

The Public Interface will allow Public Users to find and access EMF-only, public content on the DAM.

**Comment by georgemillard** [comment]
@asimonw @fannyBkane Hey guys, I have made a first pass at capturing the DAM exponential problem/principle along with definitions of Business needs, User groups and components. Please have a read of the updated comment above and share your thoughts!

**Comment by asimonw** [comment]
@georgemillard Looks good! Since you're talking about the DAM as a whole and not just the EMF interface we're currently building, where does the SMF interface sit in your user group breakdown?

**Comment by fannyBkane** [comment]
Good stuff @georgemillard ! It all makes sense to me, except for the Public user/public interface. What is the business case and the user group for that one? 
By component, do you mean interface?

**Comment by georgemillard** [comment]
@asimonw @fannyBlake As SMF is only in a prototyping stage (and therefore undefined) I thought not to include it here, though if it develops into its own interface we can add it in.

Also, as we are not currently building for Public Users, we can perhaps leave the business case for that for now, and capture it when we need it.

I used component to describe both the DAM itself (as a storage system) and the interfaces which connect to it. If another word is a better fit I'm open to suggestions :)

**Comment by fannyBkane** [comment]
While the business case is pretty clear:

> How does the DAM support EMF Business Strategy
By increasing the circularity of our content - maintaining its highest value and availability within the system.
By facilitating the implementation of our Content Strategy

Can we be more specific, and explain the user benefit in the vison?:

> The EMF Interface will allow EMF Users to find and access all items on the DAM.

'The EMF Interface enables EMF users to make their work more effective and valuable and increase collaboration opportunities  — by gaining an overview and access to the most relevant circular economy knowledge'

**Comment by MertonL** [comment]
Closing issue and have moved top level description into the wiki
