### ISSUE TITLE
Update nav bar links colour 

### ISSUE THREAD

**Issue by fannyBkane** [emfoundation/asset-manager#276]
In order to make the nav bar look neater, both links will have the same default colour and hover colour.

**Default:** 
Logo-symbol: opacity 0.6
Search icon colour: #363636 opacity 0.6 
![screen shot 2018-03-13 at 12 40 20](https://user-images.githubusercontent.com/20577339/38254384-15af0c3a-3751-11e8-89b4-67c56c66c744.png)

**Hover:**
Logo-symbol: opacity 1
Search icon colour: #363636 opacity 1
![screen shot 2018-04-03 at 15 11 11](https://user-images.githubusercontent.com/20577339/38254461-47ec5dba-3751-11e8-914e-f66a17a156f2.png)

Logo symbol sent by email
![logo-symbol](https://user-images.githubusercontent.com/20577339/38255342-834bd906-3753-11e8-80da-ce6427d3a138.png)

**Comment by fannyBkane** [comment]
Hey @MertonL looks great 🥇 Although I'm still seeing the old logo symbol (with a slate grey fill). 
![screen shot 2018-04-06 at 09 51 45](https://user-images.githubusercontent.com/20577339/38412118-88ea7302-3980-11e8-878f-4182a1b8ec24.png)

Did you receive the last png I sent - email subject title is 'Logo-symbol png in #363636 colour'?

**Comment by MertonL** [comment]
@fannyBkane Sorry about that, you're right it's still using the old png. Will update
